name: shankar_kakumani
description: Hola Internet People, Myself Shankar & I learn something new every day.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_strategy: ^0.2.0
  get: ^4.6.5
  get_it: ^7.6.0
  lottie: ^2.6.0
  animated_text_kit: ^4.2.2
  google_fonts: ^5.1.0
  just_audio: ^0.9.34
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  injectable: ^2.1.1
  flutter_constraintlayout: ^1.6.3-stable
  bloc: ^8.1.2
  flutter_svg: ^2.0.7
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: ^2.3.3
  injectable_generator: ^2.1.5


flutter:


  uses-material-design: true

  assets:
    - assets/json/
    - assets/image/
    - assets/icon/