name: shankar_kakumani
description: Hola Internet People, Myself Shankar & I learn something new every day.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_strategy: ^0.3.0
  get: ^4.6.6
  get_it: ^8.0.2
  lottie: ^3.1.3
  animated_text_kit: ^4.2.2
  google_fonts: ^6.2.1
  just_audio: ^0.9.42
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  injectable: ^2.5.0
  flutter_constraintlayout: ^1.7.0-stable
  bloc: ^8.1.4
  flutter_svg: ^2.0.14
  intl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2


flutter:


  uses-material-design: true

  assets:
    - assets/json/
    - assets/image/
    - assets/icon/